//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class amenities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public amenities()
        {
            this.exercise = new HashSet<exercise>();
        }
    
        public int id_servise { get; set; }
        public int name_id { get; set; }
        public int time_id { get; set; }
        public int gym_id { get; set; }
        public int day_id { get; set; }
        public int employees_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exercise> exercise { get; set; }
        public virtual day day { get; set; }
        public virtual employees employees { get; set; }
        public virtual gym gym { get; set; }
        public virtual name_service name_service { get; set; }
        public virtual time time { get; set; }
    }
}
