//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClub.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnesClubEntities : DbContext
    {
        public FitnesClubEntities()
            : base("name=FitnesClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amenities> amenities { get; set; }
        public virtual DbSet<beauty_services> beauty_services { get; set; }
        public virtual DbSet<beauty_servise_list> beauty_servise_list { get; set; }
        public virtual DbSet<buy> buy { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<day> day { get; set; }
        public virtual DbSet<discont> discont { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<exercise> exercise { get; set; }
        public virtual DbSet<gym> gym { get; set; }
        public virtual DbSet<name_service> name_service { get; set; }
        public virtual DbSet<period> period { get; set; }
        public virtual DbSet<subscribe> subscribe { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<time> time { get; set; }
        public virtual DbSet<type_discont> type_discont { get; set; }
        public virtual DbSet<type_subscribe> type_subscribe { get; set; }
        public virtual DbSet<type_user> type_user { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
